server:
  port: 8080

spring:
  jpa:
    show-sql: true
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/document_system
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "344035955281-88s4v4dprr6gcipgungt0kj6qmddgi4f.apps.googleusercontent.com"
            client_secret: "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"
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

jwt:
  header: Authorization
  secret: Bearer
  expiration: 123456780000


logging:
  pattern:
    console: "${spring.application.name} %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%X{X-B3-TraceId:-},%X{X-B3-SpanId:-}]){blue} [%thread] %clr(%level) %clr(%logger{36}){magenta} - %msg%n"
  level:
    ROOT: INFO
    org.springframework: WARN
    org.apache: WARN
    org.hibernate: WARN